### PR TITLE
Monika

### PR DESCRIPTION
**Pull request by Monsoegianto**
Need help on styling

### CODE REVIEW

**Comment by Peeterlee** [comment]
You should style the view in the return.
you don't need to do height and width 100% because if you do flex 1 to the view in the return it will automatically do that job.

**Comment by Peeterlee** [comment]
You may not want to put the view in the theme.

**Comment by Monsoegianto** [comment]
so comment out all the view in theme?

**Comment by Peeterlee** [comment]
put the style you had before in the view in the return and for the backgroundColor make a variable that changes based on the the value of the switch

**Comment by Monsoegianto** [comment]
do you know how i can align the text with the switch in one row

**Comment by Peeterlee** [comment]
do flexdirection:'row'

**Comment by Monsoegianto** [comment]
hi i just added my stuff
my question is how can i move the story below the switch

**Comment by Peeterlee** [comment]
sorry, you have to make a View for the text and switch to wrap them and remove flexdirection:row in the View that contains everything and put it in the view that has the text and switch

**Comment by Peeterlee** [comment]
so total you need to make 2 Views

**Comment by Monsoegianto** [comment]
so no flexdirection:row in the first view, but put it in the second view with the lorem ipsum text

**Comment by Monsoegianto** [comment]
right?

**Comment by Peeterlee** [comment]
yes correct

**Comment by Monsoegianto** [comment]
pushed new stuff

**Comment by Monsoegianto** [comment]
couple questions..

1. i did the left: 20 for the lorem ipsum text. im trying to do the same with the right, but its not working

**Comment by Peeterlee** [comment]
You could do padding like 20 maybe

**Comment by Monsoegianto** [comment]
still keep thel eft?

**Comment by Peeterlee** [comment]
no remove it

**Comment by Monsoegianto** [comment]
for the scroll view switch, i should probably make another const right haha

**Comment by Peeterlee** [comment]
yes

**Comment by Monsoegianto** [comment]
i somehow cant align the switch together

**Comment by Peeterlee** [comment]
do flexdircection:cloum for the view that has the swiches

**Comment by Peeterlee** [comment]
sorry do flexdirection:row

**Comment by Monsoegianto** [comment]
Will be doing menu. Story still needs scrollview!

**Comment by Peeterlee** [comment]
ok i will work on it

**Pull request merged**
