### PR TITLE
Patrick w

### PR DESCRIPTION
**Pull request by patrick4web**
did the color picker stuck on the changing name

### CODE REVIEW

**Comment by Peeterlee** [comment]
You need to change the value of the each picker item to the author's name too.
You don't have to change the background.

**Comment by patrick4web** [comment]
Can you check my code on the Text Change

**Comment by Peeterlee** [comment]
and change the {useState} to {bgState} between the Text component

**Comment by Peeterlee** [comment]
Change the value of useState beside const to 'Sam Marles'

**Comment by patrick4web** [comment]
for the in side the view i put this   <View style={{width: 50, height: 50, backgroundColor: 'steelblue'}} /> background color not showing up i also but it in the styles sheet

**Comment by patrick4web** [comment]
not sure why my flex direction is not working it only shows up when i did flex direction on the main.js styles sheet

**Comment by Peeterlee** [comment]
do flexdirection:row for the first View that has everything in it

**Pull request merged**
